/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author User
 */
public class Categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 102032.png")); // NOI18N
        jLabel2.setText("Imagen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 100911.png")); // NOI18N
        jLabel1.setText("Envio Gratis");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101025.png")); // NOI18N
        jButton1.setText("Categorías");

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101218.png")); // NOI18N
        jButton2.setText("Ofertas");

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101410.png")); // NOI18N
        jButton3.setText("Supermercado");

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101449.png")); // NOI18N
        jButton4.setText("Moda");

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101659.png")); // NOI18N
        jButton5.setText("Carrito");

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101758.png")); // NOI18N
        jButton6.setText("Idioma");

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 101849.png")); // NOI18N
        jButton7.setText("Iniciar Sesion");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 102234.png")); // NOI18N
        jLabel4.setText("Categoria");

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 102437.png")); // NOI18N
        jButton8.setText("Producto1");

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 102533.png")); // NOI18N
        jButton9.setText("Producto2");

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 102623.png")); // NOI18N
        jButton10.setText("Producto3");

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 102958.png")); // NOI18N
        jButton11.setText("Producto4");

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 103042.png")); // NOI18N
        jButton12.setText("Producto5");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 103321.png")); // NOI18N
        jLabel5.setText("Tendencia");

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 103413.png")); // NOI18N
        jButton13.setText("Producto1");

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 104226.png")); // NOI18N
        jButton17.setText("Producto5");

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 103536.png")); // NOI18N
        jButton14.setText("Producto2");

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 103950.png")); // NOI18N
        jButton15.setText("Producto3");

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 104055.png")); // NOI18N
        jButton16.setText("Producto4");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 104430.png")); // NOI18N
        jLabel6.setText("Descarga la App");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 104548.png")); // NOI18N
        jLabel7.setText("Información");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 104640.png")); // NOI18N
        jLabel8.setText("Play Store y Apple Store");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 104817.png")); // NOI18N
        jLabel9.setText("Redes Sociales");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 105007.png")); // NOI18N
        jLabel10.setText("Info Legal");

        jButton19.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 112801.png")); // NOI18N
        jButton19.setText("Vehiculos");

        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 113428.png")); // NOI18N
        jButton18.setText("Supermercado");

        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 113508.png")); // NOI18N
        jButton20.setText("Tecnología");

        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 113541.png")); // NOI18N
        jButton21.setText("Electrodomesticos");

        jButton22.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 113757.png")); // NOI18N
        jButton22.setText("Hogar y Muebles");

        jButton23.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 113851.png")); // NOI18N
        jButton23.setText("Deportes y Fitness");

        jButton24.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 114043.png")); // NOI18N
        jButton24.setText("Belleza y Cuidado Personal");

        jButton25.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2025-03-27 114325.png")); // NOI18N
        jButton25.setText("Accesorios para Vehiculos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18)
                            .addComponent(jButton19)
                            .addComponent(jButton20)
                            .addComponent(jButton21)
                            .addComponent(jButton22)
                            .addComponent(jButton23)
                            .addComponent(jButton24)
                            .addComponent(jButton25))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(387, 387, 387))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jButton8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton13)))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton14)
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addGap(75, 75, 75)
                                        .addComponent(jButton10)))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jButton12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton17)))))
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addComponent(jButton5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25)
                .addGap(96, 96, 96)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addComponent(jButton12))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14)
                            .addComponent(jButton15)
                            .addComponent(jButton16)
                            .addComponent(jButton17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
